- name: Configure common server features
  hosts: monicent
  become: yes
  become_method: sudo
  tasks:
    - name: install tools
      apt:
        name:
          - tmux
          - vim
          - mc
          - htop
          - git
          - wget
          - curl