- name: Install Logstash to same server with Elasticsearch
  hosts: scorista
  become: yes
  become_method: sudo
  tasks:
    - name: install tools
      apt:
        name:
          - apt-key
    - name: add Elasticsearch gpg key
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    - name: add Elasticsearch repo
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
    - name: install Metricbeat package
      apt:
        name: metricbeat
        update_cache: yes
    - name: copy Metricbeat config to server
      copy:
        src: /home/koks/fullstack/playbooks/files/metricbeat.yml
        dest: /etc/metricbeat/metricbeat.yml
        owner: root
        group: www-data
        mode: 0644
    - name: enable Metricbeat system module
      command: metricbeat modules enable system
    - name: set up the initial environment
      command: metricbeat setup -e
    - name: start Metricbeat service
      service:
        name: metricbeat
        state: started
