- name: Install Loki to server
  hosts: monicent
  become: yes
  become_method: sudo
  tasks:
    - name: setup Loki
      unarchive:
        src: https://github.com/grafana/loki/releases/download/v2.0.0/loki-linux-amd64.zip
        dest: /usr/bin
        mode: 0755
        remote_src: yes
    - name: create Loki config directory
      file:
        path: /etc/loki
        state: directory
        owner: root
        group: root
    - name: configure Loki
      get_url:
        url: https://raw.githubusercontent.com/grafana/loki/master/cmd/loki/loki-local-config.yaml
        dest: /etc/loki/loki-local-config.yaml
        owner: root
        group: root
        mode: '644'